[package]
name = "daulric/exon"
version = "0.0.45"
description = "A Framework used for Game and Other Development"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
    "*.rbxm",
    "place.project.json",
    ".gitattributes",
    ".gitignore"
]

[dependencies]