[package]
name = "daulric/devbox"
version = "0.0.24"
description = "a collection of packages made and maintained by daulric"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]