[package]
name = "daulric/exon"
version = "0.0.30"
description = "Exon - a collection of modules created to make game development easier and simple"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]