[package]
name = "daulric/dabox"
version = "0.1.0"
description = "a collection of packages made and maintained by daulric"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]