[package]
name = "daulric/dabox"
version = "0.0.5"
description = "a collection of packages made and maintained by daulric"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# OneFrame
oneframe = "daulric/oneframe@1.0.6"

# Retract
retract = "daulric/retract@0.0.22"

# RoDB
rodb = "daulric/rodb@0.0.6"

# Fission
fission = "daulric/fission@0.1.5"

# RedNet
rednet = "daulric/rednet@0.0.2"